### ISSUE TITLE
リソース単位でレンダラーを変更する方法

### ISSUE THREAD

**Issue by kumamidori** [bearsunday/BEAR.Sunday#104]
下記のようにやりたいことがあるのですが、実装方法について何かアドバイス（あるいは、そもそも何か考え方が違う等）がありましたら、教えて頂きたいです。

### やりたいこと

AリソースのGET処理内で、BリソースをGETし、取得・設定します。

Aリソース -> Bリソース

このとき、Bリソースのレンダリング結果をAリソースの情報として設定します。

ここで、コンテキスト `app` で呼び出したAリソースから、Bリソースの表現を異なるコンテキスト `html` で生成することを考えています。

たとえば、下記のようなデータの、`html` キーの値は、HTMLレンダラを使って生成し、データ全体はJSONレンダラを使いたいと考えました。

https://www.youtube.com/oembed?url=http%3A//www.youtube.com/watch%3Fv%3DbDOYN-6gdRE&format=json

```
{
    "author_name": "schmoyoho", 
    "author_url": "https://www.youtube.com/user/schmoyoho", 
    "height": 344, 
    "html": "<iframe width="459" height="344" src="https://www.youtube.com/embed/bDOYN-6gdRE?feature=oembed" frameborder="0" allowfullscreen></iframe>", 
    "provider_name": "YouTube", 
    "provider_url": "https://www.youtube.com/", 
    "thumbnail_height": 360, 
    "thumbnail_url": "https://i.ytimg.com/vi/bDOYN-6gdRE/hqdefault.jpg", 
    "thumbnail_width": 480, 
    "title": "Auto-Tune the News #8: dragons. geese. Michael Vick. (ft. T-Pain)", 
    "type": "video", 
    "version": "1.0", 
    "width": 459
}
```

### 実装方法について

コンテキストは、実行ブート時に確定するものなので、一箇所だけ別のコンテキストに変えるというようなことはできません。
そこで、自前でレンダー処理をAOPで差し込む、というやり方を考えています。

**Comment by koriym** [comment]
> コンテキストは、実行ブート時に確定するものなので、一箇所だけ別のコンテキストに変えるというようなことはできません。

これはどういうことでしょうか？

例えば以下のようにbootstrapファイルを編集して、環境やリクエストの条件によってアプリケーションコンテキストを変更することはできます。

```php
<?php
$context = strpos($_SERVER['REQUEST_URI'], '/api/') ? 'prod-hal-api-app' : 'prod-html-app';
require dirname(dirname(__DIR__)) . '/bootstrap/bootstrap.php';
```

**Comment by koriym** [comment]
またレンダラーのインジェクトをリソース単位で変更することもできます。

**Comment by kumamidori** [comment]
すみません、間違っていましたね。

appコンテキストがJsonレンダラになる場合、デフォルトだと、htmlキーの値は当然Jsonになる↓
```
  "html": {
    "foo": {
      "id": "111",
      "name": "aaa",
     ...
```

下記にはならない
```
  “html”: 
        <iframe>・・・
```

ということでした。

**Comment by koriym** [comment]
```php
class Index extends ResourceObject
{
    /**
     * @Inject
     * @Named("html")
     */
    public function setRenderer(RenderInterface $renderer)
    {
        parent::setRenderer($renderer);
    }

    public function onGet($name = 'BEAR.Sunday')
    {
        $this->body = [
            'title' => 'To ' . $name,
            'hello' => ['message' => 'Hello ' . $name]
        ];

        return $this;
    }
}
```
`RenderInterface (名前は"html")` に例えば`TwigRenderer`をバインドすればこのリソースは`TwigRenderer`でレンダリングされます。

**Comment by kumamidori** [comment]
理解できたと思います。ありがとうございました 🐏
