### ISSUE TITLE
インストール後にできるアプリケーションの名前空間

### ISSUE THREAD

**Issue by kumamidori** [bearsunday/BEAR.Sunday#105]
BEAR.Sunday のインストールで、

``composer create-project -n bear/skeleton Foo.Bar``

としたとき、できあがった空のアプリケーションの名前空間が

``MyVendor.MyProject``

として定義されます。下記のようになります。

composer.json
```
    "autoload": {
        "psr-4": {
            "MyVendor\\MyProject\\": "src/"
        }
    },
```

こうなるのは仕様でしょうか？
（この例だと、``Foo\\Bar\\`` で定義されるのでは、と思っています。）

**Comment by koriym** [comment]
`-n`オプションをつけてると質問されるベンダー名等がデフォルトになります。詳しくはcomposerのマニュアルをご覧ください。

**Comment by kumamidori** [comment]
``-n`` オプションを使う場合はベンダー名等が付かないのですね。了解です。

**Comment by koriym** [comment]
> -n オプションを使う場合はベンダー名等が付かないのですね

付かないのではなくて、本来インタラクティブに質問される部分がされずにパッケージが**デフォルト**の`MyVendor`、パッケージ名が`MyProject`になります。

```
> composer create-project --help
  ...
  -n, --no-interaction                 Do not ask any interactive question
```

**Comment by kumamidori** [comment]
昔は、ディレクトリパスの部分が名前空間になっていたような気がしたのだけれど、記憶違いだろうか、と思って確認したら、
PhpSkeleton は、仕様が変わったのですね↓

https://github.com/koriym/Koriym.PhpSkeleton/commit/8db96a93a0672df85431efe66ec035bde0959e18#diff-04c6e90faac2675aa89e2176d2eec7d8

私が気づくのが10ヶ月ほど遅かったようです 💦
