### ISSUE TITLE
QUESTION: How to handle or customize error pages?

### ISSUE THREAD

**Issue by beachwanderer** [bearsunday/BEAR.Sunday#121]
Hello guys. how do i handle or customize error pages for html module? what i wanted is to create a custom error page for html pages. Thank you in advance!

![image](https://user-images.githubusercontent.com/45347729/48993882-470b6280-f17b-11e8-83d8-423361dad4f0.png)

**Comment by koriym** [comment]
Install `TwigErrorPageModule` as written in http://bearsunday.github.io/manuals/1.0/en/html-v2.html and edit `var/templates/error.html.twig` for your own error page.

**Comment by beachwanderer** [comment]
Thank you very much sir @koriym

**Comment by koriym** [comment]
Thank you for using the BEAR.Sunday. Any feedback is welcome!
