### ISSUE TITLE
apc required

### ISSUE THREAD

**Issue by kilica** [bearsunday/BEAR.Sunday#59]
とりあえずご報告です。

composer create-project bear/skeleton MyVendor.MyPackage ~1.0@dev
cd MyVendor.MyPackage
composer install

で、該当のURLを開くと、

PHP Fatal error:  Call to undefined function Doctrine\Common\Cache\apc_fetch() in /var/www/MyVendor.MyPackage/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php on line 40

となりました。
apt-get で apc を入れるとエラーは解消。

**Comment by koriym** [comment]
報告ありがとうございます！
~~apcはオプションにします。~~
apcはオプションにしました。

**Comment by koriym** [comment]
`bootstrap.php`の

``` php
$app = (new Bootstrap)->newApp(new AppMeta(__NAMESPACE__), $context, new ApcCache);
```

この`ApcCache`の部分が問題です

対処法がいくつかあります。

1) bootstrap.phpを変更

``` php
$cache = function_exists('apc_fetch') ? new ApcCache : new FilesystemCache($appMeta->tmpDir);
$app = (new Bootstrap)->newApp($appMeta, $context, $cache);
```

2) Bootstrap::newApp()の中に1同様の処理を

3) FilesystemCacheで固定。ユーザーが環境に合わせて手で変える。

4)ApcCacheで固定。ユーザーが環境に合わせて手で変える。

**Comment by koriym** [comment]
2)にして解決しました。

> $app = (new Bootstrap)->newApp($appMeta, $context, $cache);

を

> $app = (new Bootstrap)->newApp($appMeta, $context);

という風に三番目の引数を無指定にすると`Apc`がなければファイルキャッシュを使うようになります。
