### ISSUE TITLE
More hyper media support

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Sunday#78]
- [ ] ~JSON-LD~
- [x] Siren @shingo-kumagai

**Comment by MugeSo** [comment]
It's not hyper media but how about http://swagger.io/ ?

**Comment by koriym** [comment]
would be nice.

**Comment by kuma-guy** [comment]
I'm working on Siren for renderer.

**Comment by koriym** [comment]
@shingo-kumagai  you are awesome ! You are now assignee for this issue ;)

**Comment by koriym** [comment]
BEAR.SirenModule
https://github.com/shingo-kumagai/BEAR.SirenModule

**Comment by koriym** [comment]
ping pong @MugeSo @kuma-guy

It's time to implement SwaggerModule ? anyone interested to do? :)
