### ISSUE TITLE
Is there a way to extend AbstractAppMeta?

### ISSUE THREAD

**Issue by adrian7** [bearsunday/BEAR.Sunday#84]
Currently some paths in the AbstractAppMeta class are hardcoded. Is there a way to extend the class and provide custom paths for tmp or log folder?

**Comment by koriym** [comment]
in `bootstrap.php`, You can change following code 

``` php
$app = (new Bootstrap)->getApp(__NAMESPACE__, $context);
```

to 

``` php
$appMeta = new AppMeta(__NAMESPACE__, $context);
$appMeta->tmpDir = '/path/to/tmp';
$app = (new Bootstrap)->newApp($appMeta, $context);
```

This is the simplest way to change the `log` path.

If you want have a more implementation or extra property for your application meta information.
You can have your own  application meta info class as **YourAppMeta** extends `AbstractAppMeta`.

**Comment by koriym** [comment]
@adrian7 Is this also OK ?

**Comment by adrian7** [comment]
Haven't tried it yet, but seems logical.

**Comment by koriym** [comment]
Cool. Feel free to reopen the issue when you have further question.
