### ISSUE TITLE
Bad request when accessing http://127.0.0.1:8080/weekday?year=2001&month=1&day=1

### ISSUE THREAD

**Issue by adrian7** [bearsunday/BEAR.Sunday#85]
In the tutorial ( https://bearsunday.github.io/manuals/1.0/en/tutorial.html ), there is an example showing how to start the embedded php server to test your api resource. However when trying to access the URL with curl i get a bad request response:

`php -S 127.0.0.1:8080 bootstrap/api.php`
...
`curl -v http://127.0.0.1:8080/weekday?year=2001&month=1&day=1`

`{"message":"Bad Request"}`

**Comment by koriym** [comment]
`curl -i 'http://127.0.0.1:8080/weekday?year=2001&month=1&day=1'`

Worked. Maybe you forgot single quotation ? `'`
If not the case, please `echo $e;` at  https://github.com/bearsunday/MyVendor.Weekday/blob/1.x/bootstrap/bootstrap.php#L36

**Comment by adrian7** [comment]
Right, quotation issue. My bad. :+1:

**Comment by koriym** [comment]
Don't mind. Everybody does. 😙

**Comment by koriym** [comment]
A `Pull Request` is very welcome when you want to add a line for others !
