### ISSUE TITLE
Is there a way to change the message when returning a 'Bad Request'?

### ISSUE THREAD

**Issue by adrian7** [bearsunday/BEAR.Sunday#86]
This is actually a question, but is there an easy way to change the body of the response when returning an error response code? E.g. I have this code:

```
... 
    $this['saved']  = false;
    $this['message']             = 'Please enter the message content';
    $this->headers['Status'] = '400';
}

return $this;
```

but in the response all I get is 

```
{
  "message": "Bad Request"
}    
```

**Comment by koriym** [comment]
@adrian7 Your response seems shown by `exception thrown` not by `return $this`. Would you make sure program run till `return $this` ? 

`"message": "Bad Request"` , which is shown by `VndError`, typically occur when insufficient parameters are given. (You can also check the application log at /var/log/.)

**Comment by koriym** [comment]
@adrian7 Did you solve the issue ?

**Comment by adrian7** [comment]
Yap, returning $this solved the problem.

**Comment by koriym** [comment]
Good !
