### ISSUE TITLE
リソースオブジェクト内で使っているリソースリクエストをモックする方法

### ISSUE THREAD

**Issue by kumamidori** [bearsunday/BEAR.Sunday#90]
リソースオブジェクトをモックする方法についてで、

ref. [https://github.com/bearsunday/BEAR.Sunday/issues/89#issuecomment-156904582](https://github.com/bearsunday/BEAR.Sunday/issues/89#issuecomment-156904582)

[Ray.FakeModule](https://github.com/kuma-guy/Ray.FakeModule)

を挙げて頂きました。このような実装例は参考になりとてもありがたいのですが、
自分のやりたいことを考えると、下記の点が異なると思いました
- FakeのResourceObject クラスをテストのために新規作成するよりも、モックライブラリの機能を使ってモック生成できた方が簡単で、テストコードとしても分かりやすい
- モックしたいのは、「あるテストケースのあるとき」だけなので、コンテキストグローバルに効かせたいわけではない

下記スニペットのテストをするには、`onPost`  内の `$this->resource->...` を実際に実行する必要はなく、スタブにしたいです。
何か良い方法がありますか？

``` php
class Foo extends ResourceObject
{
    use ResourceInject;

    public function onPost()
    {
        $bar = $this->resource->get->uri('app://self/aaa/bbb')->eager->request()->body;
        $query = ['bar' => $bar];
        $ro = $this->resource->post->uri('app://self/xxx/yyy')->withQuery($query)->eager->request();
        // ...
    }
}
```

**Comment by koriym** [comment]
URIをインジェクトするのはどうでしょうか、あるいは#89でもあげた方法はどうでしょうか。

> AOPで該当のメソッドをバインドしたモックインターセプターを作ってバインドする。

**Comment by koriym** [comment]
> FakeのResourceObject クラスをテストのために新規作成するよりも、モックライブラリの機能を使ってモック生成できた方が簡単で、テストコードとしても分かりやすい

何故そう思うのでしょうか？

**Comment by koriym** [comment]
リソースオブジェクトで生成されるオブジェクトを任意のもの（モックオブジェクト含む）にしたいということなら自身の`ResourceObject`ファクトリーを実装して、`FactoryInterface`にテストの時に束縛すればいいと思います。

"本物"のファクトリーはこのコードです。
https://github.com/bearsunday/BEAR.Resource/blob/1.x/src/Factory.php#L46

このようにして自分の作ったモックオブジェクトを返せば良いと思います。

**Comment by kumamidori** [comment]
> 何故そう思うのでしょうか？

これは、テスト対象のプロダクションコードがどのように設計されているのか、自分がどういう目的を持ってテストがしたいのかに依りますね。
このIssue上で一般論としては言えなかったな、と思い直しました。「モック生成できた方が」といった議論は適切ではなかったですね。

> リソースオブジェクトで生成されるオブジェクトを任意のもの（モックオブジェクト含む）にしたい

はい、上記がやりたいことです。
環境コンテキストグローバルのコンパイルタイムではなく、任意のタイミング（setUp スコープ）での binding の付け替えです。

https://github.com/bearsunday/BEAR.Sunday/issues/89#issuecomment-156904582
で既出の「テストコードで依存をセットする」で実現できることを確認しました。
- テスト対象

``` php
class OuterFoo extends ResourceObject
{
    public function onGet()
    {
        //・・・
        $ro = $this->resource->get->uri('app://self/inner/bar')
            ->withQuery($query)->eager->request();

        if ($ro->code == Code::NOT_FOUND) {
            $this->code = Code::NOT_FOUND;
            $this->body = [];

            return $this;
        }
        $this->code = Code::OK;
        $this->body = $ro->body;

        return $this;
    }
```
- Unitテスト

``` php
    public function testOnGet()
    {
        $resource = \Phake::mock(ResourceInterface::class);
        $request = \Phake::mock(RequestInterface::class);
        $stubAppRo = \Phake::mock(ResourceObject::class);

        $stubAppRo->code = 404;

        $resource->get = $resource;
        \Phake::when($resource)->uri(\Phake::anyParameters())->thenReturn($request);
        \Phake::when($request)->withQuery(\Phake::anyParameters())->thenReturn($request);
        $request->eager = $request;
        \Phake::when($request)->request()->thenReturn($stubAppRo);

        $SUT = $this->resource->newInstance('app://self/outerfoo');
        $SUT->setResource($resource);
        $resultRo = $SUT->onGet();

        $this->assertThat($resultRo->code, $this->equalTo(404));
    }
```

（改善の余地はありそうですが、）問題解決できましたので、クローズ頂いてかまいません。
ありがとうございました。
