### ISSUE TITLE
Get parameter not retrieved

### ISSUE THREAD

**Issue by john-richard** [bearsunday/BEAR.Sunday#97]
For some instance, get parameter was not able to retrieved in process.
Context "prod-api-app" is set.

Illustration 1: Source Code
![2016-08-01_1704](https://cloud.githubusercontent.com/assets/11015530/17289176/08838418-580b-11e6-9d92-3597b2edfb5d.png)

Illustration 2: In this case, we set a get parameter "offset" in the URL but it wasn't able to retrieve the data (NULL) in Illustration 1 above. We also updated to different parameter name but the output is still the same.
![2016-08-01_1653](https://cloud.githubusercontent.com/assets/11015530/17288802/58ece8b0-5809-11e6-8fc6-81bdb7cceaa4.png)

**Comment by koriym** [comment]
@janjeiar You can't get `$offset` parameter when you set `@Cacheable` annotation ?

Can you push a minimum application code and phpunit test to reproduce the issue ?

**Comment by koriym** [comment]
I create sample skeleton for this issue.
https://github.com/koriym/MyVendor.Spike

See commit history and add your own test there.

**Comment by john-richard** [comment]
@koriym-san,
    We also try to disable @Cacheable annotation and context "prod-api-app"
is set but still encounter the issue regarding parameter does not retrieved.
    I'll be checking on your current post with regards on testing the issue.
- Jan

**Comment by koriym** [comment]
I hope your test code clarify your current issue..

**Comment by koriym** [comment]
To find the real issue, Try minimize test code to focus a real problem as possible. Remove annotation, extra dependency or use minimum contexts "app". Try it in console as well as test code, not only web.  Use `xdebug` debugger to trace the code with modern IDE like PHPStorm. 

Still not figure out the problem detail ? We may need same codebase to have a same result. Please push it. I will happily investigate with your test code.

**Comment by koriym** [comment]
@janjeiar Sorry, I made `MyVendor.Spike` public now. (was private). Please let me know anything you are not sure or anything I can help.

**Comment by john-richard** [comment]
@koriym I already created a sample skeleton on my remote server but I wasn't able to commit it.
It seems that I have no permission to push on koriym/MyVendor.Spike.git
`Username for 'https://github.com': janjeiar`
`Password for 'https://janjeiar@github.com':`
`remote: Permission to koriym/MyVendor.Spike.git denied to janjeiar.`
`fatal: unable to access 'https://github.com/koriym/MyVendor.Spike.git/': The requested URL returned error: 403`

**Comment by koriym** [comment]
@janjeiar You can push your own repo ?

**Comment by john-richard** [comment]
@koriym Yes, I just pushed it in my own repo.
https://github.com/janjeiar/MyVendor.Spike.git
Branch: r97

**Comment by koriym** [comment]
missing the test code ?

**Comment by koriym** [comment]
I tried as follows.

server

```
php -S 127.0.0.1:8080 -t var/www/
```

client

```
curl -i 'http://127.0.0.1:8080/news?cat=cat1&key=key1&limit=10&offset=20'

HTTP/1.1 200 OK
Host: 127.0.0.1:8080
Connection: close
X-Powered-By: PHP/7.0.4
content-type: application/json
ETag: 1665696434
Last-Modified: Thu, 04 Aug 2016 04:02:31 GMT

{"data":"cat:cat1, key:key1, limit:10, offset:20<br>"}
```

 could not find the issue in this behavior. But I'm not sure why you put `<br>` to `offset` also.
https://github.com/janjeiar/MyVendor.Spike/blob/r97/src/Resource/App/News.php#L17

**Comment by koriym** [comment]
Let me know if I'm missing something.

**Comment by john-richard** [comment]
We often encountered the issue but not always.
At the moment during our testing, we encountered it. 
We took 3 screenshots passing 3 different offset parameter value but it retrieves same data content from the database. This was happened due to the parameter does not passed correctly or there is a problem retrieving it from Application Resource File. Kindly see images below.
![2016-08-04_1313](https://cloud.githubusercontent.com/assets/11015530/17391177/baf77c34-5a46-11e6-8c5f-4a2c9648d424.png)
![2016-08-04_1314](https://cloud.githubusercontent.com/assets/11015530/17391178/baf900c2-5a46-11e6-9fec-ac49b6a1838d.png)
![2016-08-04_1315](https://cloud.githubusercontent.com/assets/11015530/17391179/bafc46f6-5a46-11e6-939a-2d34c5e0b254.png)

**Comment by koriym** [comment]
@janjeiar Pasting screenshots here doesn't help to confirm the issue. (too much noise. even I can't search the word.)

**Comment by koriym** [comment]
@janjeiar Try to minimize the code to find the condition. (Do you need database to reproduce the error ?)  Add red test to share the problem. It is difficult to help you without code.

**Comment by john-richard** [comment]
@koriym Okay, I'll try to include the database and other logic to see if we could replicate the issue

**Comment by koriym** [comment]
Please _exclude_ first. (I'm saying "try to minimize") Passing parameters should not to have any relation with it.

**Comment by koriym** [comment]
@janjeiar have you try it in console ?

**Comment by koriym** [comment]
@janjeiar Due to inactivity I close this issue. Feel free to reopen it at any time.
