### ISSUE TITLE
500 Internal Server Error on bear.sunday skeleton 1.0.4

### ISSUE THREAD

**Issue by john-richard** [bearsunday/BEAR.Sunday#99]
I have checked out a new bear.sunday skeleton on local.
Based on the documention, I accessed it in a console but I encountered an issue during the testing
https://bearsunday.github.io/manuals/1.0/en/tutorial.html

<pre>
$ php boostrap/api.php get '/weekday?year=2016&month=8$day=24'
500 Internal Server Error
content-type: application/vnd.error+json

{"message":"500 Server Error","logref":"2734605443"}

[Ray\Compiler\Exception\NotCompiled]
MyVendor\Weekdaytwo\Resource\App
 /home/johnrichard/bear.sunday/excite/MyVendor.Weekdaytwo/var/log/last_error.log
</pre>

I also have noticed a warning in app.cli-hal-api-app.log

<pre>
[24-Aug-2016 12:09:51 Asia/Manila] PHP Warning:  ucwords() expects
exactly 1 parameter, 2 given in
/home/johnrichard/bear.sunday/excite/MyVendor.Weekdaytwo/vendor/bear/resource/src/AppAdapter.php on line 53
</pre>

Did I missed something with my testing? Or is there something wrong with
my setting?

Thank you in advance.

**Comment by ghost** [comment]
Hi! john-richard
I work for excite.

I had the same problem.
But I solved it.

## problem

ucword() added one more augument at 5.5.16 of php version.

## solving method

### pattern 1

update your php version more than 5.5.16  

### pattern 2

if you can't update php version, try the following way

#### 1

open AppAdapter.php

```
vim vendor/bear/resource/src/AppAdapter.php
```

#### 2

add the following row to @get_method at the beginning.

```
runkit_function_redefine('ucwords','$str, $delimiters="\t\r\n\f\v"','return BEAR\Resource\AppAdapter::ucwords_specific($str, $delimiters);');

```

#### 3

add the following row to @AppAdapter_class

```
public function ucwords_specific($string, $delimiters = '', $encoding = NULL)
{
  if ($encoding === NULL) { $encoding = mb_internal_encoding();}
  if (is_string($delimiters))
{
  $delimiters = str_split( str_replace(' ', '', $delimiters));
}
  $delimiters_pattern1 = array();
  $delimiters_replace1 = array();
  $delimiters_pattern2 = array();
  $delimiters_replace2 = array();
foreach ($delimiters as $delimiter)
{
  $uniqid = uniqid();
  $delimiters_pattern1[] = '{'. preg_quote($delimiter) .'}';
  $delimiters_replace1[] = $delimiter.$uniqid.' ';
  $delimiters_pattern2[] = '{'. preg_quote($delimiter.$uniqid.' ') .'}';
  $delimiters_replace2[] = $delimiter;
}
  $return_string = $string;
  $return_string = preg_replace($delimiters_pattern1, $delimiters_replace1, $return_string);
  $words = explode(' ', $return_string);
foreach ($words as $index => $word)
{
$words[$index] = mb_strtoupper(mb_substr($word, 0, 1, $encoding), $encoding).mb_substr($word, 1, mb_strlen($word, $encoding), $encoding);
}
  $return_string = implode(' ', $words);
  $return_string = preg_replace($delimiters_pattern2, $delimiters_replace2, $return_string);
  return $return_string;
}
```

**Comment by john-richard** [comment]
@yoseiyoseiyosei 
I'll will be checking your solution and try to implement it in my end.
Thank you so much for the response.

**Comment by koriym** [comment]
@john-richard @yoseiyoseiyosei Good to hear the problem solved.

However I would not recommend solution #2.  

The best solution is update PHP version 5.6+. Because PHP version 5.5.x is no more maintained since 21th July 2016. See [Supported versions](http://php.net/supported-versions.php) for more info. An unsupported version PHP should not be used in production.

**Comment by koriym** [comment]
If you really need to hack `ucwords`, You don't need to use `runkit_function_redefine`. (never use it !)

You can override function with namespace as follows.

``` php
<?php
namespace BEAR\Resource;

function ucwords($str, $delimiters = " \t\r\n\f\v")
{
    \ucwords($str);
}
```
- (Not tested. The function is need to load in [composer.json](http://stackoverflow.com/questions/24171078/composer-psr-how-to-autoload-functions).)

**Comment by koriym** [comment]
@yoseiyoseiyosei See more detail for this testing technique at http://qiita.com/okapon_pon/items/21616e14e8d4d8f1c2bc. 

@john-richard Sorry it's only written in Japanese. Ask Mugima san for help :)

**Comment by koriym** [comment]
@john-richard solved ?

**Comment by john-richard** [comment]
@koriym
I'm working with a few tasks in other project, but I'm considering the solution above with regards on updating php version. I'll get back to the testing as soon as I'm done with the other tasks.
Also, I'll will try to learn the documentation regarding testing above.
Thank you very much.

**Comment by koriym** [comment]
Welcome. It should be the best solution !
I close this issue. Feel free to reopen.
